### ISSUE TITLE
Color Of Visited Link

### ISSUE THREAD

**Issue by subhamX** [subhamX/enactus#2]
On Clicking any Link it's colour changes to **Dark Blue**. Change the behaviour of **a:visited** on Navbar from **Dark Blue** to **yellow**.  

![Link](https://user-images.githubusercontent.com/43654114/66163897-03ad3a80-e64f-11e9-9db0-a905bc4fa2af.PNG)

**Comment by suraj-sloth** [comment]
I would like to work on this issue.

**Comment by Akshay-911** [comment]
Looks awesome! I can take a look at this.
