### ISSUE TITLE
Change Text Case From UpperCase To TitleCase

### ISSUE THREAD

**Issue by subhamX** [subhamX/enactus#4]
Change the text **case** from **UpperCase To TitleCase** of all links inside **OTHER USEFUL LINKS** section in **footer** element.

**Final Output -** 
```
ENACTUS INDIA -> Enactus India
ENACTUS INTERNATIONAL -> Enactus International
```

![Capture](https://user-images.githubusercontent.com/43654114/66188450-e440fc80-e6a4-11e9-8680-8d7eca5f36de.PNG)

**Note:** You need to perform changes in all the files.

**Comment by OneEyedGhost** [comment]
I would be glad to take up this issue.

**Comment by subhamX** [comment]
@OneEyedGhost Sure. Go ahead.
