### ISSUE TITLE
Style Footer

### ISSUE THREAD

**Issue by subhamX** [subhamX/enactus#5]
You need to do the following tasks - 

~~1. Change the colour of **ENACTUS IIT ROPAR** inside **footer** to **Deep Yellow**.~~
2. On hovering any link inside the footer change the colour to **Deep Yellow**.
    `You can select all anchor tags inside footer using` -> **footer a:hover**

![Capture](https://user-images.githubusercontent.com/43654114/66188157-39c8d980-e6a4-11e9-95f7-5261ba2433f0.PNG)

https://app.leanboard.io/board/bf2dad58-f816-4d6f-99e3-39433b5d850b

**Comment by adityakmr7** [comment]
I would like to give it a try.

**Comment by subhamX** [comment]
@adityakmr7 Sure! Go ahead.

**Comment by adityakmr7** [comment]
The first one changing the color of ENACTUS IIT ROPAR can't be done I guess its a png image.

**Comment by bayuslari** [comment]
Can I working on this?

**Comment by subhamX** [comment]
@adityakmr7 Yes you are right. I have updated the description.

**Comment by adityakmr7** [comment]
@subhamX I made a PR . didn't that solved this issue ??

**Comment by subhamX** [comment]
@adityakmr7 Yeah, it did! But there are multiple people who tried to solve the same issue and was successful too. It would be unfair if I cherry-pick one PR and merge it. That's why I discontinued creating more issues. I hope you understand.

**Comment by adityakmr7** [comment]
At least you should close the issue.

**Comment by subhamX** [comment]
Doing that will make your contribution void for hacktoberfest. Will surely do that after October. :)
